print ("Please choose an activity to do!")
print ("Calculations")
print ("Words")
print ("Other")
activity = input ("Which activity would you like? ")
if (activity == "Calculations"):
  print ("Doing calculations!")
  print ("1+1 = 2")
elif (activity == "Words") or (activity == "words"):
  print ("Doing words!")
  print ("The quick brown dog jumped over the lazy fox!")
elif (activity == "other") or (activity == "Other"):
  print ("Doing other")
  print (" ################")
  print (" ##            ##")
  print (" ##   #    #   ##")
  print (" ##   #    #   ##")
  print (" ##            ##")
  print (" ##            ##")
  print (" ##   ------   ##")
  print (" ##            ##")
  print (" ################")
  print ("        III       ")
  print ("        III       ")
  print (" -----------------")
  print (" I               I ")
  print (" I               I ")
  print (" I               I ")
  print (" I     Beep      I ")
  print (" I               I ")
  print (" I               I ")
  print (" I               I ")
else:
  print ("I do not know that activity!")
print ("Activity done!")