eyes = input ("Please enter a character for Beep's eyes")

print(" ################")
print(" ##            ##")
print(" ##  ",eyes,"  ",eyes,"  ##")
print(" ##            ##")
print(" ##            ##")
print(" ##            ##")
print(" ##   ------   ##")
print(" ##            ##")
print(" ################")
print("        III       ")
print("        III       ")
print(" -----------------")
print(" I               I ")
print(" I               I ")
print(" I               I ")
print(" I     Beep      I ")
print(" I               I ")
print(" I               I ")
print(" I               I ")
print(" -----------------")