#Finds out the name and bmi of the user
print ("Hello there")
print ("")
print (" I am Beep")
print("")
name = input ("What is your name? ")
print ("Hello ",name)
height = float (input ( "How tall are you in Metres? "))
print("")
print (" Name:   ", name)
print (" Height: ", height)
print ("")
weight = float (input ( "How heavy are you in kg? "))
print ("")
print (" Name:   ", name)
print (" Height: ", height)
print (" Weight: ", weight)
print ("")
print ("  Calculating BMI")
print (".")
print ("")
print (".")
bmi = height/weight
print ("BMI = ",bmi)

