lives = int (input  ("Please enter the number of lives "))
print ("Bleep has ", lives, " lives")
energy = int (input  ("Please enter the energy level "))
print ("Bleep has ", energy, " energy")
shields = int (input  ("Please enter the shield level "))
print ("Showing display")
print ("")
print ("Lives:   ", lives * "♥")
print ("Energy:  ", energy * "♦")
print ("Shields: ", shields * "♦")

